import jwt from 'jsonwebtoken';

// This is the authantication middleware for cheking the action of the user.
const auth = async(req,res,next)=>{
    try {
        const token=req.headers.authorization.split(" ")[1];    //extracting token from request header.
        const isCustomAuth = token.length <500;     // checking token is generated by google or our system.
        let decodedData; 

        if(token && isCustomAuth){    // control go into this section if there is token and it is generated by our system.
            decodedData = jwt.verify(token,'test');     // verifying the token
            req.userId = decodedData?.id;   // assiging the request userId with token userId.

        }
        else{                           //control will go into this section if there is token and it is generated by google means if signin was happend using google id.
            decodedData= jwt.decode(token); // decoding the token and getting data from token.
            req.userId = decodedData?.sub;  // assigning the request userId with unique userId assigned by google to the user.
        }

        next();     // it will call the next middleware.

    } catch (error) {
        console.log(error);
    }
}

export default auth;
